export const parallaxItems = [
  {
    src: "/images/bg/bg.webp",
    className: "bg-img",
    speedx: 0.3,
    speedy: 0.38,
    speedz: 0,
    rotation: 0,
    distance: -200,
    alt: "bg-img",
  },
  {
    src: "/images/fog/fog-7.webp",
    className: "fog-7",
    speedx: 0.27,
    speedy: 0.32,
    speedz: 0,
    rotation: 0,
    distance: 850,
    alt: "fog-7",
  },
  {
    src: "/images/mountain/mountain-10.webp",
    className: "mountain-10",
    speedx: 0.195,
    speedy: 0.305,
    speedz: 0,
    rotation: 0,
    distance: 1100,
    alt: "mountain-10",
  },
  {
    src: "/images/fog/fog-6.webp",
    className: "fog-6",
    speedx: 0.25,
    speedy: 0.28,
    speedz: 0,
    rotation: 0,
    distance: 1400,
    alt: "fog-6",
  },
  {
    src: "/images/mountain/mountain-9.webp",
    className: "mountain-9",
    speedx: 0.125,
    speedy: 0.155,
    speedz: 0.15,
    rotation: 0.02,
    distance: 1700,
    alt: "mountain-9",
  },
  {
    src: "/images/mountain/mountain-8.webp",
    className: "mountain-8",
    speedx: 0.1,
    speedy: 0.11,
    speedz: 0,
    rotation: 0.02,
    distance: 1800,
    alt: "mountain-8",
  },
  {
    src: "/images/fog/fog-5.webp",
    className: "mountain-8",
    speedx: 0.16,
    speedy: 0.105,
    speedz: 0,
    rotation: 0.02,
    distance: 1900,
    alt: "fog-5",
  },
  {
    src: "/images/mountain/mountain-7.webp",
    className: "mountain-7",
    speedx: 0.1,
    speedy: 0.1,
    speedz: 0,
    rotation: 0.09,
    distance: 2000,
    alt: "mountain-7",
  },
  {
    src: "/images/mountain/mountain-6.webp",
    className: "mountain-6",
    speedx: 0.065,
    speedy: 0.05,
    speedz: 0.05,
    rotation: 0.12,
    distance: 2300,
    alt: "mountain-6",
  },
  {
    src: "/images/fog/fog-4.webp",
    className: "fog-4",
    speedx: 0.135,
    speedy: 0.1,
    speedz: 0,
    rotation: 0,
    distance: 2400,
    alt: "fog-4",
  },
  {
    src: "/images/mountain/mountain-5.webp",
    className: "mountain-5",
    speedx: 0.08,
    speedy: 0.05,
    speedz: 0.13,
    rotation: 0.1,
    distance: 2550,
    alt: "mountain-5",
  },
  {
    src: "/images/fog/fog-3.webp",
    className: "fog-3",
    speedx: 0.11,
    speedy: 0.018,
    speedz: 0.13,
    rotation: 0,
    distance: 2800,
    alt: "fog-3",
  },
  {
    src: "/images/mountain/mountain-4.webp",
    className: "mountain-4",
    speedx: 0.059,
    speedy: 0.024,
    speedz: 0.35,
    rotation: 0.14,
    distance: 3200,
    alt: "mountain-4",
  },
  {
    src: "/images/mountain/mountain-3.webp",
    className: "mountain-3",
    speedx: 0.04,
    speedy: 0.018,
    speedz: 0.32,
    rotation: 0.05,
    distance: 3400,
    alt: "mountain-3",
  },
  {
    src: "/images/fog/fog-2.webp",
    className: "fog-2",
    speedx: 0.15,
    speedy: 0.0115,
    speedz: 0,
    rotation: 0,
    distance: 3600,
    alt: "fog-2",
  },
  {
    src: "/images/mountain/mountain-2.webp",
    className: "mountain-2",
    speedx: 0.0235,
    speedy: 0.013,
    speedz: 0.42,
    rotation: 0.15,
    distance: 3800,
    alt: "mountain-2",
  },
  {
    src: "/images/mountain/mountain-1.webp",
    className: "mountain-1",
    speedx: 0.027,
    speedy: 0.018,
    speedz: 0.53,
    rotation: 0.2,
    distance: 4000,
    alt: "mountain-1",
  },
  {
    src: "/images/sun/sun-rays.webp",
    className: "sun-rays hide",
    // speedx: 0.027,
    // speedy: 0.018,
    // speedz: 0.53,
    // rotation: 0.2,
    // distance: 0,
    alt: "sun-rays",
  },
  {
    src: "/images/black-shadow.webp",
    className: "black-shadow hide",
    // speedx: 0,
    // speedy: 0,
    // speedz: 0,
    // rotation: 0,
    // distance: 0,
    alt: "black-shadow",
  },
  {
    src: "/images/fog/fog-1.webp",
    className: "fog-1",
    speedx: 0.12,
    speedy: 0.01,
    speedz: 0,
    rotation: 0,
    distance: 4200,
    alt: "black-shadow",
  },
];
